# Generated by Django 3.2.13 on 2022-10-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.CharField(choices=[('★', 'first'), ('★★', 'second'), ('★★★', 'third'), ('★★★★', 'fourth'), ('★★★★★', 'fifth')], max_length=10),
        ),
    ]
