# Generated by Django 3.2.13 on 2022-10-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_tite',
            new_name='movie_title',
        ),
    ]
