# Generated by Django 3.2.13 on 2022-10-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_movie_tite_review_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_title',
            field=models.CharField(choices=[('블랙 아담', '블랙 아담'), ('리멤버', '리멤버'), ('자백', '자백'), ('인생은 아름다워', '인생은 아름다워'), ('에브리씽 에브리웨어 올 앳 원스', '에브리씽 에브리웨어 올 앳 원스'), ('공조2: 인터내셔날', '공조2: 인터내셔날'), ('귀못', '귀못'), ('극장판 짱구는 못말려: 수수께끼! 꽃피는 천하떡잎학교', '극장판 짱구는 못말려: 수수께끼! 꽃피는 천하떡잎학교')], max_length=30),
        ),
    ]
