# Generated by Django 3.2.13 on 2022-10-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_review_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_title',
            field=models.IntegerField(choices=[(1, '블랙 아담'), (2, '리멤버'), (3, '자백'), (4, '인생은 아름다워'), (5, '에브리씽 에브리웨어 올 앳 원스'), (6, '공조2: 인터내셔날'), (7, '귀못'), (8, '극장판 짱구는 못말려: 수수께끼! 꽃피는 천하떡잎학교')]),
        ),
    ]
