# Generated by Django 3.2.13 on 2022-10-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_recomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='body',
            field=models.CharField(max_length=150),
        ),
    ]
