# Generated by Django 3.2.13 on 2022-10-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_recomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
